### PR TITLE
Bug 539991 - Try to add the known_hosts

### PR DESCRIPTION
**Pull request by mickaelistria**
Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=539991

**Comment by mbarbero** [comment]
You should not even need the "defaultMode: 420". I was too quick pasting another config.

**Comment by mickaelistria** [comment]
I've updated the PR, but build is still failing because of known_hosts.
What I don't understand is whether the volume is mounted automatically to the default jnlp container that's used for the copy? Should I explicitly declare a 'jnlp' container in the podTemplate, referencing the eclipse CBI jnlp image directly? What's the name of the docker image so I can reference it?

**Comment by mbarbero** [comment]
Yes, you should add a jnlp image and mount it inside it (or just use the other container to push). That's a limitation from the Kubernetes Jenkins plugin. The docker image is

eclipsecbi/jenkins-jnlp-agent@sha256:356386dcc1fafd296d8dbe206831c73e061ce603bd371810785454c064cefcb1

**Pull request merged**
