### PR TITLE
Update language servers

### PR DESCRIPTION
**Pull request by vrubezhny**
The following LSs will be updated to the latest versions:
    
typescript@3.9.7
typescript-plugin-css-modules@2.4.0
yaml-language-server@0.9.0
firefox-debugadapter@2.9.0
debugger-for-chrome@4.12.8
eslint@7.5.0
@typescript-eslint/eslint-plugin@3.2.0
@typescript-eslint/parser@3.2.0
@angular/language-service@10.0.4
@angular/language-server@0.1000.4
    
Fixes: #475 

Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Can you please open a CQ for these?

**Comment by vrubezhny** [comment]
@mickaelistria Could you please review chrome-debug-adapter downloading related changes?

**Comment by mickaelistria** [comment]
Using VSCode CLI to get the extension is a smart way to do it!
However, is it multi-platform? Can I run this build on Linux or Mac now? Paths seem very Linux specific.

**Comment by vrubezhny** [comment]
> Using VSCode CLI to get the extension is a smart way to do it!
> However, is it multi-platform? Can I run this build on Linux or Mac now? Paths seem very Linux specific.

In theory, paths can be configured in some Arch-specific blocks. But I'm not sure if I am able and I can do it  more or less quickly with tycho. Feel free to help with it. :)

However this was the only way I could beat the `"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).` error on chrome-debug-adapter download.

Did you spot how many of the latest PRs are built successfully? Marketplace is evil.

**Comment by vrubezhny** [comment]
The following CQs are created:

- NPM LS modules and dependencies - https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22413
- VSCode debugger for chrome - https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22414

**Comment by mickaelistria** [comment]
Test pass, awesome!
Let's merge it now, as we're allowed to merge witht the CQs open (only release needs to wait for CQ to be released).

**Pull request closed without merging**
