### PR TITLE
Issue #396: which() to inspect PATH environment var for executables

### PR DESCRIPTION
**Pull request by daemonblade**
Please review, as I'm doing this blind. I don't have a dev-env for wildwebdeveloper set up.

### CODE REVIEW

**Comment by akurtakov** [comment]
@mbooth101 Mat, I would like to hear your opinion on that from flatpak/sandbox POV.

**Comment by mbooth101** [comment]
Wouldn't it be better to simply change ```/bin/bash``` to ```/bin/sh``` ?

On Linux ```/bin/sh``` is a symlink to the distro's default shell anyway. On Fedora/RHEL it is a symlink to bash, on Debian it is a symlink to dash, etc.

**Comment by daemonblade** [comment]
I'm puzzled as to why /bin/sh (or /bin/bash) `which` would discover something on ${PATH} that a manual inspection wouldn't.

**Comment by mbooth101** [comment]
> I'm puzzled as to why /bin/sh (or /bin/bash) `which` would discover something on ${PATH} that a manual inspection wouldn't.

We use a shell because a user may have additional paths configured in their ```~/.profile``` (or ```~/.bash_profile```) that we could not check without invoking a login shell, i.e.: ```/bin/sh -l```

**Comment by daemonblade** [comment]
In which case I agree that the quickest way to do this is change the shell to /bin/sh

**Comment by mickaelistria** [comment]
@daemonblade Ok, so can you please amend your patch and `push --force` to your branch to update the PR. By the way, you'll need to add the "Signed-Off-By..." footer in your commit with  `git commit --amend --signoff` and ensure you signed the Eclipse Contributor Agreement at https://accounts.eclipse.org/legal/eca/

**Comment by daemonblade** [comment]
@mickaelistria Reading thru' the original code, /bin/bash uses the "-l" option. Unfortunately, this option isn't present in POSIX sh.

Can I suggest that the Java based PATH inspection snippet be place before the current Runtime.exec() attempt? I've amended my patch to show you what I mean.

**Comment by mickaelistria** [comment]
I'm fine with this patch as long as 1. CI tests still pass on regular Linux, 2. you confirm it fixes your issue and 3. @mbooth101 confirms it doesn't break Flatpak deliveries.

**Comment by mbooth101** [comment]
> @mickaelistria Reading thru' the original code, /bin/bash uses the "-l" option. Unfortunately, this option isn't present in POSIX sh.
> 
> Can I suggest that the Java based PATH inspection snippet be place before the current Runtime.exec() attempt? I've amended my patch to show you what I mean.

Yeah, I think that's fine. When no exe is found in any PATH, then it will fall through and check with which.

**Comment by mickaelistria** [comment]
So that's good for me, good for CI, good for @mbooth101 
@daemonblade Do you confirm it works for you and it's good to merge?

**Comment by daemonblade** [comment]
Yes, good to merge

**Comment by mickaelistria** [comment]
Thanks all, and particularly @daemonblade !

**Pull request merged**
