### PR TITLE
Limit LSP4E dependency to version <= 0.23 due to the API--breaking ch…

### PR DESCRIPTION
**Pull request by vrubezhny**
…anges

### CODE REVIEW

**Comment by akurtakov** [comment]
That is not fine as that would make wwd unusable with other LSP based editors that develop against master

**Comment by mickaelistria** [comment]
@vrubezhny if you can directly include a newer version of the code that works against latest release and current master of LSP4E, and restrict the ranges minimal version instead, that would be best.

**Comment by vrubezhny** [comment]
> @vrubezhny if you can directly include a newer version of the code that works against latest release and current master of LSP4E, and restrict the ranges minimal version instead, that would be best.

That's the goal, but at the moment if we don't restrict LSP4E versions and users are updating to the latest LSP4E snapshot - they fail to run WWD/M2E-Core. And nothing prevents the users from such an update, plus it's 2023-06 RC1 milestone today.

**Comment by vrubezhny** [comment]
Closing as not accepted

**Pull request closed without merging**
