### PR TITLE
Fix JS/TS Refactoring Rename JUnit Test

### PR DESCRIPTION
**Pull request by vrubezhny**
Due to change in  `typescript-language-server@2.2.0` that implements `prepareRename` request now we have to implicitly set the new value for an identofier im `Refactoring->Rename` dialog during the test.

See: [`feat: support textDocument/prepareRename request #628` change](https://github.com/typescript-language-server/typescript-language-server/pull/628)

### CODE REVIEW

**Comment by vrubezhny** [comment]
License check failure is due to https://github.com/eclipse/dash-licenses/issues/195 - not related to the PR

**Comment by mickaelistria** [comment]
Can you please describe in commit message what makes that change is now necessary?

**Comment by vrubezhny** [comment]
> Can you please describe in commit message what makes that change is now necessary?

Updated: https://github.com/eclipse/wildwebdeveloper/pull/1001#issue-1494329901

**Comment by vrubezhny** [comment]
> > Can you please describe in commit message what makes that change is now necessary?
> 
> Updated: [#1001 (comment)](https://github.com/eclipse/wildwebdeveloper/pull/1001#issue-1494329901)

This PR should fix failing test in https://github.com/eclipse/wildwebdeveloper/pull/999

**Comment by mickaelistria** [comment]
Good, thanks!

**Pull request merged**
