### PR TITLE
Issue #220 - Enable support for node 11 and 12

### PR DESCRIPTION
**Pull request by jabby**
Signed-off-by: Gautier de Saint Martin Lacaze <gautier.desaintmartinlacaze@gmail.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Should we instead use a versionRange and assume compatibility with future versions as well?

**Comment by jabby** [comment]
Fair question. It will reduce time to maintain this part of code. Next version of node will be released the 2019-10-22. 
I think it's easiest to react if we find a problem with a new version. In the other hand, I checked in node_modules. Some restrictions suggest, we should not use node in version 7 or 9 or 11. I think it's because these versions are not LTS. 


One example from  `vscode-jsonrpc@4.0.0`
Engine versions are 
```json
{
  ...
  "engines": {
    "node": ">=8.0.0 || >=10.0.0"
  },
  ...
}
```

**Comment by mickaelistria** [comment]
I think we at least need to have support for 13 if it's to be released soon. Some early-adopters will try it and showing them an error message is less interesting to them and to Wild Web Developer than having them using hte tool, and maybe finding issues.

**Comment by jabby** [comment]
I added the version 13 to the list of supported node runtime. 
If you are ok with this change, we can merge. Update 2 times per year this is not so difficult.

**Comment by mickaelistria** [comment]
> If you are ok with this change, we can merge.

Yes, it's a valuable improvement. Feel free to merge it.

> Update 2 times per year this is not so difficult.

I'm more concerned about us remembering to do it at the right time ;)

**Comment by rombert** [comment]
Great, thanks to both of you for the rapid fix.

**Pull request merged**
