### PR TITLE
Update target platform to 4.12 / 2019-06 release

### PR DESCRIPTION
**Pull request by jabby**

### CODE REVIEW

**Comment by mickaelistria** [comment]
At this point, as we won't produce a new build for 2019-06, it might be better to go directly to 4.13/2019-09

**Comment by akurtakov** [comment]
It would be nice if we can make extra release targeting 2019-06 with updated lsp4xml.

**Comment by mickaelistria** [comment]
Ok, then let's accept this patch as it.
Thanks @jabby

**Comment by jabby** [comment]
@mickaelistria you're welcome

@akurtakov About lsp4xml. Do you know when lsp4xml 0.8.0 will be released? I will be happy to do the corresponding CQ and eventually merge your PR or create a new one.

**Pull request merged**
