### PR TITLE
Update target platform to 4.11

### PR DESCRIPTION
**Pull request by jabby**
Signed-off-by: Gautier de Saint Martin Lacaze <gautier.desaintmartinlacaze@gmail.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Can you please change the version of the target-platform pom.xml and its reference in the parent pom and -as a consequence- the version of the parent pom and all its references to 0.3.0?

**Comment by jabby** [comment]
Just one question before updating all version numbers. 
Should we update the target-platform version to 0.2.0 or 0.3.0. Actually it's only 0.1.0

**Comment by mickaelistria** [comment]
0.3.0 would be better. I think it's best to keep the TP and parent pom at the same version as the project when we change them.
We should probably have updated to 0.2.0 during the previous cycle.

**Comment by mickaelistria** [comment]
The parent reference in org.eclipse.wildwebdeveloper.xml is missing an update.
And I think the TP reference in root pom.xml misses it as well.

**Comment by jabby** [comment]
Indeed @mickaelistria you're right. I miss some update of parent / target-platform version number. 
Thanks for your review.

**Comment by mickaelistria** [comment]
Thank Jenkins for that, it's him who did put a red cross on GitHub ;)

**Comment by jabby** [comment]
@mickaelistria I'm not familiar with baseline validation during build. Can you help me about this one ? 

```
[ERROR] Baseline and reactor have same fully qualified version, but with different content
Baseline /home/jenkins/workspace/Wildwebdeveloper_PR-150-X2I5EK3JDZTFMMI3QMVYDJY3DKHFXMQPAMS2AEYMQ46X4BGBW7DA/.m2/repository/p2/osgi/bundle/org.eclipse.wildwebdeveloper.xml/0.1.0.201903111934/org.eclipse.wildwebdeveloper.xml-0.1.0.201903111934.jar and reactor /home/jenkins/workspace/Wildwebdeveloper_PR-150-X2I5EK3JDZTFMMI3QMVYDJY3DKHFXMQPAMS2AEYMQ46X4BGBW7DA/org.eclipse.wildwebdeveloper.xml/target/org.eclipse.wildwebdeveloper.xml-0.1.0-SNAPSHOT.jar are made of different bytes
```

**Comment by mickaelistria** [comment]
This was merged, thanks.
https://github.com/eclipse/wildwebdeveloper/commit/da3e0d5c2ee482a02dc30a6986166221ad34f354 fixes the build issue.

**Pull request merged**
