### PR TITLE
Draft: [Waiting for CQ] Update language servers

### PR DESCRIPTION
**Pull request by vrubezhny**
The following LSs will be updated to the latest versions:
typescript@3.8.3
typescript-plugin-css-modules@2.3.0
yaml-language-server@0.8.0
firefox-debugadapter@2.8.0
typescript-eslint-language-service@3.0.0
eslint@7.1.0
@typescript-eslint/eslint-plugin@3.1.0
@typescript-eslint/parser@3.1.0
@angular/language-service@9.1.9
@angular/language-server@0.901.9

Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Thanks for this good patch Victor! I opened https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22235 to track IP, we'll merge as soon as CQ is resolved.

**Comment by mickaelistria** [comment]
Log says "[INFO] MavenProject: org.eclipse.wildwebdeveloper:org.eclipse.wildwebdeveloper:0.5.8-SNAPSHOT @ /home/jenkins/agent/workspace/Wildwebdeveloper_PR-435/org.eclipse.wildwebdeveloper/pom.xml
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [pack200, sources]"
We need to change some "payload" file so newer version is used.

I suggest we
1. remove package-lock.json from .gitignore
2. add it to maven-clean-plugin

With that, it will force a commit whenever a dependency change so the replacement wouldn't happen.

**Comment by vrubezhny** [comment]
Now the log says:
```
[INFO] No baseline version MavenProject: org.eclipse.wildwebdeveloper:org.eclipse.wildwebdeveloper:0.5.8-SNAPSHOT @ /home/jenkins/agent/workspace/Wildwebdeveloper_PR-435/org.eclipse.wildwebdeveloper/pom.xml
```
So, I suppose it doesn't replace the artefact with the baseline version. Is it correct?

However, some tests now started to fail:
https://ci.eclipse.org/wildwebdeveloper/job/Wildwebdeveloper/job/PR-435/2/testReport/org.eclipse.wildwebdeveloper.tests/TestAngular/testAngular/

**Comment by mickaelistria** [comment]
@vrubezhny in the package-lock you sent me for that, version of yaml-language-server is 0.6.1, typescript is 3.7.2... It looks like this package-lock.json is outdated and comes from some older build. Can you please retry, making sure package-lock.json is deleted first?

**Comment by mickaelistria** [comment]
@vrubezhny in the package-lock you sent me for that, version of yaml-language-server is 0.6.1, typescript is 3.7.2... It looks like this package-lock.json is outdated and comes from some older build. Can you please retry, making sure package-lock.json is deleted first?

**Comment by mickaelistria** [comment]
The latest version of this patch seems to build the right package-lock.json, I'll use it to update the CQ.

**Comment by vrubezhny** [comment]
Yes, without the latest changes package-lock.json wasn't cleared before the build. 
Now it should be cleared with `maven-clean-plugin`.

**Comment by mickaelistria** [comment]
I recently merged a patch that's supposed to avoid the issue of replaced content when embedded LS are changing. Can you please rebase your patch on top of master? That should help.

**Comment by mickaelistria** [comment]
Related CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22235

**Comment by mickaelistria** [comment]
This was merged as Wild Web Developer can leverage parallel IP checks and merge code before CQs are approved (but not release changes which still require CQ approval).

**Pull request merged**
