### PR TITLE
Use npm ci instead of npm install

### PR DESCRIPTION
**Pull request by jabby**
Signed-off-by: Gautier de Saint Martin Lacaze <gautier.desaintmartinlacaze@gmail.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Thanks!

**Comment by mickaelistria** [comment]
@jabby: it seems like `npm ci --no-bin-links --ignore-scripts` ignore the 2 flags, and using it usually creates the symbolic links, that we don't want to use in Wild Web Developer. Do you know a possible way to use both `npm ci` and avoid creation of symlinks?

**Comment by jabby** [comment]
If I understand correctly the npm documentation (not the best one), it should not infore the 2 flags. https://docs.npmjs.com/cli/ci.html

Maybe problem comes from package-lock.json. I checked and it contains direct local links to tar.gz files.

**Comment by jabby** [comment]
Which symbolic links did you find? I tried on my laptop and at least --ignore-scripts is ok.

If I use `npm ci` I get an error about postinstall script from node-debug2 1.25.5
If I use `npm ci --ignore-scripts`, there is no error. 

And I was not able to find a symbolic link in node_modules.

**Comment by mickaelistria** [comment]
I see symlinks after `npm ci --no-bin-links --ignore-scripts` in the `node_modules/.bin` folder. Those symlinks generate an error later during tests provisioning.

**Comment by jabby** [comment]
FYI 
https://github.com/eclipse/wildwebdeveloper/pull/205#issuecomment-516337617

**Pull request merged**
