### PR TITLE
Update to typescript 3.5.3 and ls 0.3.8.

### PR DESCRIPTION
**Pull request by akurtakov**
Fix for #187

Signed-off-by: Alexander Kurtakov <akurtako@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Can you please check locally whether manually reproducing the test case scenario that are failing works as expected or fails too?
The combination of all those LS is getting more and more fragile, and it could be that updating only typescript can cause issue on other parts now.

**Comment by akurtakov** [comment]
All tests pass locally sometimes - TestTypeScript.testHTMLinTSXFile fails randomly but it has been failing that way prior to this patch too.

**Comment by jabby** [comment]
@mickaelistria I agree with you when you said that updating some language servers will broke others. 

I just checked how vscode plugins like vetur (for vue.js) worked. In fact each plugins seems to have his own node_modules. It's duplicate a lot of files between some plugins but updating one does not break others.

May be we should start to separate some language servers into separate plugins? I think we can keep JSON, HTML and CSS language server together as there are part of vscode by default.

**Comment by mickaelistria** [comment]
@jabby Do you know if it's possible to get multiple versions of the same module in node_modules and to have node picking some dependencies that seem more safely compatible?

**Comment by mickaelistria** [comment]
@akurtakov tests should be a bit improved. Please try rebasing and cross fingers ;)

**Pull request merged**
