### PR TITLE
WIP : enable vue support

### PR DESCRIPTION
**Pull request by jabby**
Signed-off-by: Gautier de Saint Martin Lacaze <gautier.desaintmartinlacaze@gmail.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Hey @jabby , is there any blocker about it? Or is it "just" a matter of finding some time to fix/polish it?

**Comment by jabby** [comment]
It just a matter of time. I need to polish and properly test this feature.  And of course I need to feel all CQs.

But, because there is a but, my main concern is about the build with npm. I have some troubles on my laptop with npm 6 vs npm 5. There is some big changes about the dependency resolution. 
Other though about npm is the use of `npm ci` instead of `npm install` during the build of wild web developer. I think it will be a good idea but we need to do this in another PR.  see https://docs.npmjs.com/cli/ci for more information about npm cli. 

So before polishing this work, we need to update the build of wild web developer and maybe fill many CQs.

**Comment by mickaelistria** [comment]
> So before polishing this work, we need to update the build of wild web developer and maybe fill many CQs.

I recently learned that for npm modules, we can submit a single CQ with all modules in it.

**Comment by jabby** [comment]
> I recently learned that for npm modules, we can submit a single CQ with all modules in it.

I don't understand. We can create one CQ with all modules listed in the description and attach the corresponding node_modules folder ?

**Comment by jabby** [comment]
If yes, it will be easiest to submit new dependencies but it will be harder to know if one module is already approved through another CQ.

**Comment by mickaelistria** [comment]
> We can create one CQ with all modules listed in the description and attach the corresponding node_modules folder ?
> If yes, it will be easiest to submit new dependencies but it will be harder to know if one module is 
already approved through another CQ.

> I don't understand.

Given your comments and concerns, it just seems like you actually understood everything ;)

**Comment by jabby** [comment]
I continue my work on this feature. It start to work but there is still some work to do. 
In fact I check how the configuration is synchronized between the client and the language server and I discovered that vue-languager-server use a lot of configuration from the vscode workspace. 

See https://github.com/vuejs/vetur/blob/master/client/client.ts#L19-L31

I don't know how to do the same properly.

**Comment by jabby** [comment]
@mickaelistria do you have an idea?

**Comment by mickaelistria** [comment]
Sirry,I didn't have the opportunity to invrstigate it and probably won't
have it before next week.
>
>

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by mickaelistria** [comment]
@jabby Do you plan to work again on this soon-ish?

**Comment by jabby** [comment]
Yes I plan to work on this. I had a problem with last version of vetur on my laptop. Maybe it was a problem between 2 versions of typescript. I will rebase my local work on master and then try again.

**Comment by jabby** [comment]
Close as https://github.com/eclipse/wildwebdeveloper/pull/210 fix this issue

**Pull request closed without merging**
