### PR TITLE
Add TypeScript website debug instructions to FAQ

### PR DESCRIPTION
**Pull request by AObuchow**
Enable sourceMaps in Chrome Launch Debug Delegate

Signed-off-by: Andrew Obuchowicz <aobuchow@redhat.com>

### CODE REVIEW

**Comment by AObuchow** [comment]
Note: this only shows how to debug TypeScript with Chrome (I haven't figuredo out how to get it working in Firefox yet, it might require more work for Firefox). It also assumes that the `out` folder lives in the project folder. A future patch should be made to allow modification of the sourceMaps path.

**Comment by AObuchow** [comment]
If anyone wants to verify this works, https://code.visualstudio.com/docs/typescript/typescript-debugging provides an examplary project to test it out. (It works for me)

**Comment by jabby** [comment]
I will try this tomorrow.

**Comment by mickaelistria** [comment]
That looks very good and I trust this works, so let's merge it now, and improve it if necessary in the future.
It would be interesting to also document the case of a plain "microservice" written in typescript (ie without an html file as entrypoint).

**Comment by AObuchow** [comment]
> I will try this tomorrow.

Thanks @jabby, despite the fact this was merged it would still be greatly appreciated if you could test it out to ensure it's valid.

**Comment by AObuchow** [comment]
> It would be interesting to also document the case of a plain "microservice" written in typescript (ie without an html file as entrypoint).

Yes this is something I've wanted to do for a while as I think microservice debuging/development is essential for web developers in 2020.

I'm almost certain it should be possible (I had it working on a local server which used webpack + source maps), although a modification will need to be made to the launch configuration to accept a URL instead of just files.

**Pull request merged**
