### PR TITLE
Enhanced language server TSX test to verify functionality on xml notation

### PR DESCRIPTION
**Pull request by kascaks**
This PR contains an enhancement of tsx test to verify fix for https://github.com/eclipse/wildwebdeveloper/issues/980

### CODE REVIEW

**Comment by vrubezhny** [comment]
@kascaks Have you signed Eclipse CLA using the same e-mail address that was used for this PR? If not, please do sign it at https://accounts.eclipse.org/user/eca

**Comment by kascaks** [comment]
> @kascaks Have you signed Eclipse CLA using the same e-mail address that was used for this PR? If not, please do sign it at https://accounts.eclipse.org/user/eca

Can this be done without creating eclipse account?
Maybe via this clause of the CLA?
`(c) The contribution was provided directly to me by some other
        person who certified (a), (b) or (c) and I have not modified
        it`

**Comment by vrubezhny** [comment]
@kascaks Normally we wouldn't merge without agreeing with the contributor agreement. What's the problem with creating an Eclipse.org account?

**Comment by kascaks** [comment]
It's just that it seems like an overkill to have to create account to push 7 lines of code. But, I did try to do it. However, I'm getting error that "The email address you entered is not valid. Please contact webmaster..." :) So, really not such an easy task :)

**Comment by vrubezhny** [comment]
> It's just that it seems like an overkill to have to create account to push 7 lines of code. But, I did try to do it. However, I'm getting error that "The email address you entered is not valid. Please contact webmaster..." :) So, really not such an easy task :)

I believe the e-mails like `*+*@users.noreply.github.com` will never be accepted by eclipse.org, neither by most of the other services. Do you have another e-mail registered to try registering at Eclipse.org? (The PR is to be re-created with that other e-mail if accepted)

**Comment by mickaelistria** [comment]
> it seems like an overkill to have to create account to push 7 lines of code

It is, but there have been some legal arguments for less than that. The ECA allows mostly to avoid possible issue by making you clearly state you're OK to contribute this code under the license.

@waynebeaton Can you help @kascaks in succeeding to sign the ECA?

**Comment by kascaks** [comment]
I managed to create account and I signed the agreement

**Comment by mickaelistria** [comment]
@kascaks Thanks for signing the ECA, we'll do our best to merge it ASAP..
@vrubezhny license-check jobs are failing. is there some incompatibility between Maven/Tycho versions here?

**Comment by vrubezhny** [comment]
@mickaelistria it looks like yes, latest tychoo snapshot makes the build to fail on building maven dependencies if maven <3.9 is used.

I tried to fix windowsPR and licence check to use maven 3.9.2, so windowsPR functionality is restored, but I can't make it for maven projects check action we depend on at the moment.

**Comment by vrubezhny** [comment]
@kascaks Thanks for your contribution!

**Pull request merged**
