### PR TITLE
Update Embedded Node.js Runtime to latest LTS version (v.18.14.0)

### PR DESCRIPTION
**Pull request by vrubezhny**
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.14.0

### CODE REVIEW

**Comment by vrubezhny** [comment]
An IP Team Review request is created: [git/github/nodejs/node/v18.14.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6942)

**Comment by vrubezhny** [comment]
For some reason, build on Jenkins fails to execute JUnit tests which stably hang/deadlock while running node.js v.18.14.0, which doesn't happen when the previous node.js version (v.18.13.0) is used. Windows_PR build as well as building on my local environment (f36, amd64) are quite stably successful.
I've restored  [the PR for the previous node.js version](https://github.com/eclipse/wildwebdeveloper/pull/1089) and [the IP Team Review request for node.js v.18.13.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6271) while investigating this issue.

**Comment by mickaelistria** [comment]
Will we use it now that we have #1116 ; or should we close?

**Comment by vrubezhny** [comment]
@mickaelistria Exactly. When https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6942 is resolved, I'm going immediately created an IPTeam review request for v.18.14.2 which is to be resolved as soon as Dash Bot passes it according to the IP Due Diligence process that short circuits on service releases. 
So, v.18.14.2 is the candidate to the next embedded Node.js version.

**Pull request closed without merging**
