### PR TITLE
VSCode 1.54

### PR DESCRIPTION
**Pull request by mickaelistria**
Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
VSCode ships newer major version of the vscode-json-languageservice so it's not compatible with yaml-language-server any more and requires to duplicate multiple version of libraries, leading to path too long. I suggest we simply wait for yaml-language-server to use newer major of vscode-json-language server before updating VSCode.

**Comment by akurtakov** [comment]
Sounds good. Please open issue for yaml-language-server so we know what exactly we wait for.

**Comment by mickaelistria** [comment]
Reported https://github.com/redhat-developer/yaml-language-server/issues/405

**Comment by mickaelistria** [comment]
Submitted CQs http://dev.eclipse.org/ipzilla/show_bug.cgi?id=23161 and http://dev.eclipse.org/ipzilla/show_bug.cgi?id=23160 , other deps are approved by dash-license tool.
Let's merge (CQ only prevent release, not merge).

**Pull request merged**
