### PR TITLE
Switch to yaml-language-server 0.11.0

### LINKED ISSUE #244: [Firefox Debug] Pre-set file in Launch Configuration when editor has focus
1. Open some HTML file in an Eclipse IDE editor, ensure editor is active (has focus)
2. Debug As > Launch Firefox Debugger > New Configuration
EXPECTED: the current file path is pre-set in the Launch Configuration
GOT: Empty file path

### LINKED ISSUE #372: YAML should not support tabs.
According to this: https://yaml.org/spec/1.2/spec.html#id2777534
`In YAML block styles, structure is determined by indentation. In general, indentation is defined as a zero or more space characters at the start of a line.

To maintain portability, tab characters must not be used in indentation, since different systems treat tabs differently. Note that most modern editors may be configured so that pressing the tab key results in the insertion of an appropriate number of spaces.

The amount of indentation is a presentation detail and must not be used to convey content information.

Each node must be indented further than its parent node. All sibling nodes must use the exact same indentation level. However the content of each sibling node may be further indented independently..`
Wild web developer allows us to use YAML files with tabs.
https://imgur.com/58hVbWM
Is there any change to do in generic editor to allows convering tabs to space?

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #372 

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by jeffmaury** [comment]
Tested and it works with a schema and code completion.
However, if I enter the following in an empty file:

`mytag:`

and then ENTER then the cursor is on next line and column 0 (no indentation at all) but that was perhaps the same before;. Maybe @evidolob can comment

**Comment by jabby** [comment]
@jeffmaury Are you sure it's about #244 ?

**Comment by jeffmaury** [comment]
> 
You are right, wrong repo issue link, I updated it

**Comment by evidolob** [comment]
> However, if I enter the following in an empty file:
> 
> `mytag:`
> 
> and then ENTER then the cursor is on next line and column 0 (no indentation at all) but that was perhaps the same before;.

Yaml-ls does't do indentation on text edits, we fix indentation on codecompletion.

**Comment by mickaelistria** [comment]
@jeffmaury Can you please rebase it?

**Comment by mickaelistria** [comment]
Opened CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22605

**Comment by mickaelistria** [comment]
Merged as 50b320cd65e5ebcb5e57ad1c8d39458033610db5

**Pull request closed without merging**
