### PR TITLE
Update LSs & NPM Modules - typescript-language-server 2.1.0

### PR DESCRIPTION
**Pull request by vrubezhny**
typescript-language-server  2.0.1  --> 2.1.0

Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>

### CODE REVIEW

**Comment by vrubezhny** [comment]
The following IP Team requests created for the issue:

typescript-language-server v.2.1.0:: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/4090

**Comment by akurtakov** [comment]
Have you looked about the possibility for dependabot handling these updates?

**Comment by vrubezhny** [comment]
> Have you looked about the possibility for dependabot handling these updates?

I thought about it, but haven't looked if I can tune dependabot to handle it yet.

**Comment by mickaelistria** [comment]
A while ago, I had extracted the list of npm deps in a package.json, but moved back to pom.xml for some reason I don't remember. It could be worth retrying that approach, then dependabot would be able to process it.
But all that is hypothetical.

**Pull request merged**
