### PR TITLE
Update to lsp4xml 0.7.0

### PR DESCRIPTION
**Pull request by akurtakov**
lsp4xml has a lot of new features and fixes so let's not delay on using
it as osgi lib.

Signed-off-by: Alexander Kurtakov <akurtako@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
This needs a CQ.

**Comment by akurtakov** [comment]
I'll file it now.

**Comment by angelozerr** [comment]
@akurtakov @mickaelistria  I think you should wait for 0.8.0 which provides a lot of features (performance, XSD types support with codelens, highlight), etc

**Comment by akurtakov** [comment]
CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20320

**Comment by akurtakov** [comment]
> @akurtakov @mickaelistria I think you should wait for 0.8.0 which provides a lot of features (performance, XSD types support with codelens, highlight), etc

We can do another release once 0.8.0 is out.

**Comment by akurtakov** [comment]
CQ approved.

**Pull request merged**
