### PR TITLE
Update Maven build machinery.

### PR DESCRIPTION
**Pull request by akurtakov**
* download-maven-plugin to 1.4.2
* tycho to 1.4.0
* preoject source encoding to UTF-8
* maven prereq to 3.3.9
* jacoco to 0.8.4
* maven-clean-plugin to 3.1.0 (to silence maven warning on startup)

### CODE REVIEW

**Comment by mickaelistria** [comment]
Updating LSP4XML requires a CQ.

**Comment by akurtakov** [comment]
Oops, I didn't ment the second commit to end up in this pull request. Can you fetch the first one only for now ?

**Comment by akurtakov** [comment]
Regarding the CQ - it needs a commiter to file it.

**Comment by mickaelistria** [comment]
>  Can you fetch the first one only for now ?

Done.

> Regarding the CQ - it needs a commiter to file it.

I think it's a bit late to change that before SimRel, let's delay it for next week.
I'm nominating you as a committer.

**Comment by akurtakov** [comment]
> > Can you fetch the first one only for now ?
> 
> Done.
> 
> > Regarding the CQ - it needs a commiter to file it.
> 
> I think it's a bit late to change that before SimRel, let's delay it for next week.
> I'm nominating you as a committer.

Heh, I should have written it clearer (my hope was for existing committer to do the work) but so be it :)

**Comment by mickaelistria** [comment]
> Heh, I should have written it clearer (my hope was for existing committer to do the work) but so be it :)

You wrote it clearly and I understood it as you meant it; I'm intentionally acting as if I understood differently ;)

**Pull request closed without merging**
