### PR TITLE
Move to LemMinX 0.13.1

### PR DESCRIPTION
**Pull request by mickaelistria**
Change-Id: I5d39720794095fcac0f4d6dbc064da2e7788e54f
Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Review by jabby — APPROVED** [review]

**Comment by mickaelistria** [comment]
I'll first try it against m2e and the lemminx-maven extension to make sure nothing is broken.

**Comment by gautier-desaintmartinlacaze-cbp** [comment]
Should we create a new CQ?

**Comment by mickaelistria** [comment]
No, because lemminx is an Eclipse.org project, there is no need for a CQ.

**Comment by jabby** [comment]
I won't merge this one unless you said it's ok.
Thanks for your answer.

**Comment by mickaelistria** [comment]
Test with m2e and lemminx-maven are good, let's merge.

**Pull request merged**
