### PR TITLE
Issue #96 - Test server connection

### PR DESCRIPTION
**Pull request by mickaelistria**
Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by jabby** [comment]
@mickaelistria The build is ok. The code seems ok for me. 
Do you think it is sufficient for validating the server connection and avoid a problem like reported in #95 ?

**Comment by jabby** [comment]
I checked again. I'm not sure tests are executed. 
The command line for launching the build is : `mvn clean verify -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true -DskipTests -PpackAndSign -Dmaven.repo.local=/home/jenkins/workspace/Wildwebdeveloper_PR-97-P43JE6BTL7IPH7DSJHQFJWWE77643NP6NMA2P4GGTFVZHOTKO3DQ/.m2/repository`

The skipTests seems odd. 
I will check the jenkins configuration.

**Comment by jabby** [comment]
Ok. If you need anything about node / npm. Ask me.

**Comment by mickaelistria** [comment]
Ok, thanks. At the moment, the issue is more about the vncserver. I've asked about it on the cbi-dev@eclipse.org mailing-list.

**Comment by mickaelistria** [comment]
I merged a patch to have it: https://github.com/eclipse/wildwebdeveloper/commit/b7990a45eba3b54320ccd9332a6ed6802f948034
It includes a Docker image which we can use for build+test and tweaks to the Jenkinsfile to consume this image.

**Pull request closed without merging**
