### PR TITLE
OnEnterRules support for html files

### PR DESCRIPTION
**Pull request by angelozerr**
OnEnterRules support for html files

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
I think we need a CQ to allow inclusion of this language-configuration file. I created https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24255

**Comment by angelozerr** [comment]
Why we need not a CQ for JS/TS OnEnterRules file?

**Comment by mickaelistria** [comment]
> Why we need not a CQ for JS/TS OnEnterRules file?

We already had a CQ and approval for those when we included the language-configuration for the 1st time. The changes are then increments without strong IP matter, so no CQ required.

**Comment by angelozerr** [comment]
The languag econfiguration for HTML already exists at https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/language-configurations/html/language-configuration.json

I have just renamed to `language-configuration.jsonc`  (like I did for JST/TS) to avoid error with comments when you open it in Eclipse IDE.

**Comment by mickaelistria** [comment]
Ah OK, my bad. So no need for a CQ indeed!

**Pull request merged**
