### PR TITLE
Update Embedded Node.js Runtime to latest LTS version (v14.15.1)

### PR DESCRIPTION
**Pull request by vrubezhny**
Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Did you already open a CQ for that? If yes, can you please link it here?

**Comment by akurtakov** [comment]
There was issue creating new CQs. @vrubezhny it's supposed to be fixed now according to https://bugs.eclipse.org/bugs/show_bug.cgi?id=569219 so please do it now.

**Comment by vrubezhny** [comment]
> Did you already open a CQ for that? If yes, can you please link it here?

The CQ #22853is created: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22853 - Node.js v.14.15

**Comment by jabby** [comment]
Replaced by #596

**Pull request closed without merging**
