### PR TITLE
Update Embedded Node.js Runtime to latest version (v.16.9.0)

### PR DESCRIPTION
**Pull request by vrubezhny**
Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Did you already open a CQ about it?

**Comment by vrubezhny** [comment]
> Did you already open a CQ about it?

A CQ is created for Embedding Node.js v.16.9.0:  https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23720

**Comment by mickaelistria** [comment]
ca@vrubezhny CQ is approved; can you please rebase on top of master and then we can merge?

**Comment by mickaelistria** [comment]
Great, thanks!

**Pull request merged**
