### PR TITLE
Use vscode-json-languageserver from npmjs

### PR DESCRIPTION
**Pull request by mickaelistria**
Instead of extracting it from VSCode binary

Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Requires CQ, but currently Eclipse.org infra is KO. Will open CQ as soon as it's back to work.

**Comment by mickaelistria** [comment]
CQ http://dev.eclipse.org/ipzilla/show_bug.cgi?id=20443

**Comment by mickaelistria** [comment]
@jabby This is where I see the symlinks with `npm ci --ignore-links --no-bin-links`, if I keep `npm install` in the pom, it's ok, with `npm ci`, I see symlinks. Can you please give it a try?

**Comment by mickaelistria** [comment]
Replaced with https://github.com/eclipse/wildwebdeveloper/pull/209 .
@jabby Apparently 'npm ci' works fine. The issue is probably on my end.

**Comment by jabby** [comment]
FYI information I think npm ci should honored --no-bin-links. 
I created an issue on the npm bugtracker https://npm.community/t/npm-ci-no-bin-links-is-not-honored/9180

**Pull request closed without merging**
