### PR TITLE
Fix typo in readme

### PR DESCRIPTION
**Pull request by jabby**

### CODE REVIEW

**Comment by mickaelistria** [comment]
Thanks!

**Comment by jabby** [comment]
@mickaelistria I don't know how to update the Eclipse Marketplace entry for Wild Web Developer. There is the typo too. 

https://marketplace.eclipse.org/content/eclipse-wild-web-developer-web-development-eclipse-ide

**Comment by mickaelistria** [comment]
I've added you as a maintainer for the Marketplace entry. You can now edit it (there is an "edit" tab). I let you give it a try and fix the typo ;)

**Comment by jabby** [comment]
Done. Thanks @mickaelistria

**Pull request merged**
