### PR TITLE
Calculate JVM path via java.home sys property

### LINKED ISSUE #601: Eclipse keeps on starting new instances of itself
Hello! 👋🏻 

I've just updated from Wild Web Developer XML tools 0.10.3.202011132012 to Wild Web Developer XML tools 0.10.4.202101050902. Each time I open a _pom.xml_ file in a Maven project, a new Eclipse IDE instance is started on top of the running one.

I'm able to reproduce the problem on both my Windows and macOS machines.

### PR DESCRIPTION
**Pull request by BoykoAlex**
Fixes #601

Change-Id: Ide9f161ae5a29e81692faf15b6d571bbca8c82ff
Signed-off-by: BoykoAlex <aboyko@pivotal.io>

### CODE REVIEW

**Comment by mickaelistria** [comment]
@PyvesB can you please try it and report whether it fixes your issue?

**Comment by angelozerr** [comment]
It's not related to this PR, but I think more and more that LSP4E should provide an abstract class like `JavaProcessStreamConnectionProvider` which should take care java  stuff (computeJavaPath, getProxySettings etc).

**Comment by PyvesB** [comment]
> @PyvesB can you please try it and report whether it fixes your issue?

Yep, will check over the weekend or on Monday.

**Comment by PyvesB** [comment]
I checked out the master branch of this repository. Unfortunately, I'm not able to reproduce in the context of the PDE IDE. When you run WildWebDeveloper as an Eclipse Application, it spawns a new IDE workbench directly with the Java executable specified in the launch configuration. Unlike what I described in https://github.com/eclipse/wildwebdeveloper/issues/601#issuecomment-760947435, it won't be using the software called "Eclipse" installed on your macOS or Windows operating system, so the problem won't occur.

**Comment by mickaelistria** [comment]
@PyvesB would you mind trying a local `mvn clean verify -DskipTests` and installing the local build from repository/target/repository in a "regular" Eclipse IDE to see whether this works in real life?

**Comment by PyvesB** [comment]
Tried the above on my macOS - I can confirm that the problem is fixed there. 👍🏻

**Comment by mickaelistria** [comment]
Perfect, thanks guys!

**Pull request merged**
