### PR TITLE
Export package containing extension interface

### PR DESCRIPTION
**Pull request by mickaelistria**
Mark it as x-friends with m2e for the moment to make explicit it's not
100% set in stone and we use m2e to consolidate it.

Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by AObuchow** [comment]
Looks good to me, just need to pull this into my eclipse workspace to validate everything then we can merge. Will do shortly.

**Comment by mickaelistria** [comment]
I do have the m2e-core patch in my workspace, I can take care of updating it if you want.

**Comment by AObuchow** [comment]
> I do have the m2e-core patch in my workspace, I can take care of updating it if you want.

That would be greatly appreciated, but I do know it's getting late in France so I can handle this if you would like :)

**Comment by mickaelistria** [comment]
I'll take care of it.

**Comment by AObuchow** [comment]
> I'll take care of it.

Ok thank you, it's appreciated.
Checking out this commit now in my workspace.

**Comment by AObuchow** [comment]
Looks good to me. Going to merge now.

**Pull request merged**
