### PR TITLE
Upgrade Yaml Language Server from 0.8.0 to 0.9.0 #475

### PR DESCRIPTION
**Pull request by apupier**
nota: I was unable to build locally the master and so unable to test it properly

### CODE REVIEW

**Comment by apupier** [comment]
failure of PR doesn't seems related to the PR: `script returned exit code 143`

**Comment by apupier** [comment]
> failure of PR doesn't seems related to the PR: `script returned exit code 143`

don't who did it but the relaunch of the job is in success. Thanks

**Comment by mickaelistria** [comment]
@vrubezhny Do you see any objection with that change? Would you like to open the CQ?

**Comment by vrubezhny** [comment]
I'm preparing a larger set of modules to be updated. YAML LS 0.9.0 looks like a safe candidate to update, so I'm going to include @apupier's   commit into the PR.
@mickaelistria Yes, I'll try openning a CQ for YAML LS and other updates

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipse/wildwebdeveloper/pull/484

**Comment by mickaelistria** [comment]
Thanks @apupier

**Pull request closed without merging**
